#!/usr/bin/env node
'use strict';
// release.js — one-command Prism release build (installer + blockmap).
//
// Use this INSTEAD of `npm run dist:legacy`, because icon generation has to
// happen first: electron-builder bakes win.icon into the PE at build time, so a
// stale white-background icon gets compiled straight into the .exe.
//
//   1. regenerate icons from the source logo
//   2. VERIFY the white matte is actually gone (refuse to continue otherwise)
//   3. remove artifacts from previous builds so they cannot be mistaken for
//      current ones
//   4. run electron-builder
//   5. verify the expected installer + blockmap landed
//
// Usage:
//   npm run release                     build, commit/push source, and publish if token is set
//   npm run release -- --name Spectrum  override the chosen name for this build
//
// A release commit and branch push follow a verified local build; GitHub
// Releases publishing remains optional and requires a GitHub token.
//
// A release is published as "Prism <version> — <name>". The name is derived
// from the features in scripts/release-notes.md, which is also what the
// suggestions are read from, so the name always describes the actual release.

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const { PNG } = require('pngjs');
const {
  createReleaseNotes,
  releaseTitle,
  resolveReleaseName,
  updateReleaseName,
  githubApiRequest,
  replaceExistingRelease
} = require('./release-helper');
const releaseGit = require('./release-git');

const ROOT = path.join(__dirname, '..');
const ASSETS = path.join(ROOT, 'assets');
const SIZES = [16, 24, 32, 48, 64, 128, 256, 512];

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const VERSION = pkg.version;

// Previous builds wrote Shroom-named artifacts. They cannot be salvaged by
// renaming: the product name and the icon are compiled into the PE, so only a
// rebuild replaces them. Listed explicitly rather than globbed, so this can
// never reach anything else sitting in the project root.
// Matches a built installer or blockmap for ANY version, old brand or new:
//   Prism-1.0.2-x64.exe   Prism-1.0.2-portable.exe   Prism-1.0.2-x64.exe.blockmap
//   ShroomBrowser-1.0.1-x64.exe  (etc.)
// A hardcoded version list left every previous release behind, so the root
// accumulated one installer set per build. Cleaning by pattern keeps exactly one
// set - the portable and x64 installers plus the x64 blockmap. The shape is
// strict, so nothing that is not a Prism/ShroomBrowser build artifact can match;
// Prism-1.0.2-x64.__uninstaller.exe deliberately does not (and is created during
// the build, after this runs).
const ARTIFACT_RE = /^(?:Prism|ShroomBrowser)-[\d.]+-(?:x64|portable)(?:\.exe|\.exe\.blockmap)$/;

// latest.yml is regenerated by electron-builder only when a `publish` block is
// configured. The stale copy survived every build still pointing at
// PrismBrowser-1.0.2-x64.exe - an old-brand name for a file that does not exist.
const STALE_ARTIFACTS = ['latest.yml'];



function log(msg) { console.log(msg); }
function fail(msg) { console.error('\nERROR: ' + msg + '\n'); process.exit(1); }

// electron-builder publishes with tagPrefix (default "v" for GitHub), so the
// release the client fetches is this tag, not a guessed spelling.
function tagName() {
  const prefix = (pkg.build && pkg.build.publish && pkg.build.publish.tagPrefix) || 'v';
  return prefix + VERSION;
}

// `--name` overrides the automatic name for one specific build. Everything else
// is derived, so a plain `npm run release` never asks anything and produces the
// same name for the same notes.
function parseArgs(argv) {
  const args = { name: '' };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--name' || arg === '--release-name') args.name = argv[++i] || '';
    else if (arg.startsWith('--name=')) args.name = arg.slice('--name='.length);
    else if (arg.startsWith('--release-name=')) args.name = arg.slice('--release-name='.length);
    else if (arg === '--help' || arg === '-h') args.help = true;
  }
  return args;
}

function notesTemplate() {
  const file = path.join(__dirname, 'release-notes.md');
  return fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
}

const ARGS = parseArgs(process.argv.slice(2));
const NOTES_TEMPLATE = notesTemplate();

function resolveNameForBuild() {
  return resolveReleaseName({ requested: ARGS.name, notesText: NOTES_TEMPLATE });
}

function resolveGitHubConfig() {
  const publish = pkg.build && pkg.build.publish;
  if (!publish || publish.provider !== 'github' || !publish.owner || !publish.repo) {
    fail('GitHub release publishing requires build.publish.provider, owner, and repo in package.json.');
  }
  return { owner: publish.owner, repo: publish.repo };
}

function requestGitHub(apiPath, method, token, body) {
  return githubApiRequest({
    hostname: 'api.github.com',
    path: apiPath,
    method,
    body,
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: 'Bearer ' + token,
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'Prism-Release-Script'
    }
  });
}

async function replaceSameVersionRelease() {
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  if (!token) return;
  const { owner, repo } = resolveGitHubConfig();
  const tag = tagName();
  const basePath = '/repos/' + encodeURIComponent(owner) + '/' + encodeURIComponent(repo);
  const count = await replaceExistingRelease({
    basePath,
    tag,
    request: (apiPath, method) => requestGitHub(apiPath, method, token)
  });
  if (count) log('  removed ' + count + ' published release(s) for ' + tag + '; the same tag will be recreated with this build.');
  else log('  no existing GitHub release for ' + tag + '; a new release will be created.');
}

// Name the release that electron-builder has just created.
//
// This runs after the upload on purpose: the assets and the tag are already
// live by this point, so failing to set a cosmetic title must not be reported as
// a failed release - the installer is out and updating normally either way.
async function renamePublishedRelease(name) {
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  if (!token) return;
  try {
    const { owner, repo } = resolveGitHubConfig();
    const basePath = '/repos/' + encodeURIComponent(owner) + '/' + encodeURIComponent(repo);
    await updateReleaseName({
      basePath,
      tag: tagName(),
      name,
      request: (apiPath, method, body) => requestGitHub(apiPath, method, token, body)
    });
    log('  named the release "' + name + '"');
  } catch (error) {
    console.warn('  WARNING: could not name the release: ' + error.message);
    console.warn('  The release itself is published and updating normally; only its title is missing.');
    console.warn('  Rename it on the releases page, or re-run the release with a token.');
  }
}

// electron-builder resolves the GitHub release body from releaseInfo, or from
// a release-notes.md in the project directory. Generate that file from the
// maintained template so the published description is comprehensive rather than
// a bare version string. The generated copy is a build artifact (gitignored).
function writeReleaseNotes(name) {
  const templateFile = path.join(__dirname, 'release-notes.md');
  if (!fs.existsSync(templateFile)) {
    console.warn('  no release-notes.md template found - the release description will be the default version only.');
    return;
  }
  const file = path.join(ROOT, 'release-notes.md');
  fs.writeFileSync(file, createReleaseNotes(fs.readFileSync(templateFile, 'utf8'), VERSION, name), 'utf8');
  log('  wrote comprehensive release notes to ' + path.relative(ROOT, file));
}

// shell:false when we spawn node directly. On Windows, routing an absolute
// path like "C:\Program Files\nodejs\node.exe" through cmd.exe re-splits it on
// the space and the command fails for a reason that looks nothing like a path
// bug.
function run(cmd, args, useShell = true) {
  log('\n> ' + cmd + ' ' + args.join(' '));
  const r = spawnSync(cmd, args, { cwd: ROOT, stdio: 'inherit', shell: useShell });
  if (r.error) fail(r.error.message);
  if (typeof r.status === 'number' && r.status !== 0) fail(cmd + ' exited with code ' + r.status);
}

function generateIcons() {
  run(process.execPath, ['scripts/process-logo.js'], false);
}

// The defect this guards against: process-logo.js reads a white-background
// render. If the matte is not knocked out, the artwork bounds cover the entire
// canvas and every icon ships as a white square — which looks blank on Prism's
// dark chrome rather than obviously wrong. Sampling the border is enough to
// tell a real transparent icon from a white one, and costs almost nothing.
function verifyIconsTransparent() {
  for (const s of SIZES) {
    const file = path.join(ASSETS, 'icon-' + s + '.png');
    if (!fs.existsSync(file)) fail('missing ' + file + ' — icon generation did not produce it');
    const png = PNG.sync.read(fs.readFileSync(file));
    let opaque = 0;
    const at = (x, y) => png.data[(y * png.width + x) * 4 + 3];
    for (let x = 0; x < png.width; x++) {
      if (at(x, 0) === 255) opaque++;
      if (at(x, png.height - 1) === 255) opaque++;
    }
    for (let y = 0; y < png.height; y++) {
      if (at(0, y) === 255) opaque++;
      if (at(png.width - 1, y) === 255) opaque++;
    }
    if (opaque > 0) {
      fail('icon-' + s + '.png still has ' + opaque + ' fully opaque border pixels.\n' +
           '  The white background was not knocked out, so this icon is a white\n' +
           '  square that reads as a blank tile on Prism\'s dark chrome.\n' +
           '  Raise OPAQUE_FLOOR in scripts/process-logo.js and re-run.');
    }
  }
  log('OK  all ' + SIZES.length + ' icon sizes have transparent borders');
}

function removeIfPresent(target) {
  if (!fs.existsSync(target)) return false;
  fs.rmSync(target, { force: true, recursive: true });
  log('  removed ' + path.relative(ROOT, target));
  return true;
}

function cleanStale() {
  log('\nCleaning previous-build artifacts:');
  let n = 0;
  for (const entry of fs.readdirSync(ROOT)) {
    if (ARTIFACT_RE.test(entry)) { removeIfPresent(path.join(ROOT, entry)); n++; }
  }
  for (const name of STALE_ARTIFACTS) if (removeIfPresent(path.join(ROOT, name))) n++;
  if (removeIfPresent(path.join(ROOT, 'win-unpacked'))) n++;
  // dist/ is a whole earlier output location, from when directories.output was
  // "./dist". It still holds a ShroomBrowser blockmap and a second stale
  // win-unpacked/ with the old logo inside its .exe. The current config writes
  // to the project root, so nothing recreates it — remove the whole directory.
  if (removeIfPresent(path.join(ROOT, 'dist'))) n++;
  // Build OUTPUTS only. This deliberately does not touch assets/shroom.ico,
  // assets/ShroomIcon-raw.png or the src/main/shroom-search*.js forwarders:
  // deleting source from a build command means that if anyone ever re-adds a
  // require() of one of those stubs, `npm run release` silently deletes a
  // source file instead of reporting a broken import. Those leftovers are
  // harmless and unreferenced; remove them by hand.
  if (!n) log('  nothing to clean');
}

// Read the packaged asar back and assert the entry point and every internal
// page really made it in. `files` in package.json is a glob list, so a silent
// packaging regression is otherwise invisible until the installed app shows a
// blank page — which is exactly the failure this guards against.
function verifyPackagedPages() {
  const asarPath = path.join(ROOT, 'win-unpacked', 'resources', 'app.asar');
  if (!fs.existsSync(asarPath)) {
    log('  (skipped: win-unpacked/resources/app.asar not found)');
    return;
  }
  let asar = null;
  for (const name of ['@electron/asar', 'asar']) {
    try { asar = require(name); break; } catch (_) { /* try the next name */ }
  }
  if (!asar) {
    log('  (skipped: no asar module available to inspect the archive)');
    return;
  }
  const needed = [
    'src/main/main.js',
    'src/shell/shell.css',
    'src/pages/newtab.html',
    'src/pages/search.html',
    'src/pages/history.html',
    'src/pages/bookmarks.html',
    'src/pages/downloads.html',
    'src/pages/passwords.html',
    'src/pages/extensions.html',
    'src/pages/privacy.html',
    'src/pages/settings.html',
    'src/pages/blocked.html',
    'src/pages/error.html'
  ];
  // Read each entry straight out of the archive rather than comparing against
  // a listing. listPackage() formats paths differently across asar versions
  // (leading slash or not, and the Rust rewrite may differ again), and getting
  // that wrong reports every file as missing on a perfectly good build.
  if (typeof asar.extractFile !== 'function') {
    log('  (skipped: asar module has no extractFile)');
    return;
  }
  const missing = [];
  for (const f of needed) {
    // On Windows the archive stores entries with backslash separators
    // ("\src\main\main.js"). extractFile() looks up by exact path, so a
    // forward-slash lookup misses every entry and reports a perfectly good
    // build as empty. Try both spellings.
    let found = false;
    for (const variant of [f, f.replace(/\//g, path.sep), f.replace(/\//g, '\\')]) {
      try { asar.extractFile(asarPath, variant); found = true; break; }
      catch (_) { /* try the next spelling */ }
    }
    if (!found) missing.push(f);
  }
  if (missing.length) {
    let sample = '';
    try {
      const list = asar.listPackage(asarPath) || [];
      sample = '\n  First entries in the archive: ' + JSON.stringify(list.slice(0, 6));
      const srcish = list.filter((e) => /main|pages|shell/i.test(e));
      sample += '\n  Entries matching main|pages|shell: ' + JSON.stringify(srcish.slice(0, 6)) +
                '  (' + srcish.length + ' total)';
    } catch (e) {
      sample = '\n  (could not list the archive: ' + e.message + ')';
    }
    // Reported, not fatal. This check runs after the artifacts already exist,
    // so failing here cannot protect anything - it can only block installation
    // of a perfectly good installer. It has produced false positives twice
    // (asar stores backslash-separated paths on Windows), and a checker with no
    // track record should not hold veto power. Treat what it prints as a reason
    // to look, not as a reason to stop.
    console.error(
      '\nWARNING: could not confirm the packaged app.asar contains ' + missing.length + ' file(s):\n' +
      '  ' + missing.join('\n  ') + sample + '\n' +
      '  The installer HAS been built. Install it; if internal pages render blank,\n' +
      '  this is the thing to investigate.\n');
    return;
  }
  log('OK  app.asar contains the entry point and all ' + needed.length + ' internal pages');
}

function verifyArtifacts() {
  // directories.output is "./", so artifacts land in the project root.
  const expected = [
    'Prism-' + VERSION + '-x64.exe',
    'Prism-' + VERSION + '-x64.exe.blockmap',
    'Prism-' + VERSION + '-portable.exe'
  ];
  const missing = expected.filter((name) => !fs.existsSync(path.join(ROOT, name)));
  log('\nArtifacts in ' + ROOT + ':');
  for (const name of expected) {
    if (missing.includes(name)) { log('  MISSING  ' + name); continue; }
    const mb = (fs.statSync(path.join(ROOT, name)).size / (1024 * 1024)).toFixed(1);
    log('  OK       ' + name + '  (' + mb + ' MB)');
  }
  if (missing.length) {
    fail('electron-builder finished but ' + missing.length + ' expected artifact(s) are missing:\n' +
         '  ' + missing.join('\n  ') + '\n' +
         '  Check the electron-builder output above for the real cause.');
  }
}

// --help has to be handled before anything with a side effect runs. The icon
// pass rewrites assets/ and cleanStale() deletes the previous build's
// installer, blockmap and latest.yml, so a help request that reached them would
// destroy a build the user did not ask to rebuild. This block deliberately runs
// with no `ask`, so printing help never prompts for a name.
if (ARGS.help) {
  const preview = resolveReleaseName({ requested: ARGS.name, notesText: NOTES_TEMPLATE });
  console.log('Prism release script\n');
  console.log('  npm run release                     build, commit/push the current branch, then publish as "' + releaseTitle(VERSION, preview.name) + '"');
  console.log('  npm run release -- --name Spectrum  build, commit/push, then publish with an explicit name');
  console.log('  npm run release -- --help           show this message\n');
  console.log('  The name is chosen automatically from the "New in this release"');
  console.log('  section of scripts/release-notes.md, and becomes the GitHub release');
  console.log('  title and the notes heading. Override it for one build with --name.');
  console.log('  The tag stays v' + VERSION + ': the updater reads the version from');
  console.log('  latest.yml, falling back to the tag, and never from the title.\n');
  console.log('  Release source changes are committed and the current branch is pushed after a successful build.\n');
  console.log('  Set GITHUB_TOKEN to publish the GitHub release. Without it, the local build and Git push still run, but no release is uploaded.\n');
  process.exit(0);
}

log('Prism ' + VERSION + ' release build');
log('='.repeat(46));

if (!fs.existsSync(path.join(ROOT, 'node_modules', 'electron-builder'))) {
  fail('electron-builder is not installed. Run `npm install` first.');
}

// Refuse a detached checkout, staged changes, or missing remote BEFORE the
// build cleanup starts. After the installer is verified, source changes are
// committed and the current branch is pushed before any GitHub release is replaced.
try {
  const gitState = releaseGit.checkGitReady(ROOT);
  log('  Git source commit will push branch ' + gitState.branch + ' to ' + gitState.remote);
} catch (error) {
  fail('Git publishing is not ready: ' + error.message);
}

generateIcons();
verifyIconsTransparent();
cleanStale();

// Publishing is what gives the auto-updater a feed to read, so it happens
// whenever a token is available -- but never before the local build is verified.
//
// A same-version run replaces the existing published release for that version
// instead of failing: electron-builder refuses to upload to a release published
// more than two hours ago, and GitHub will not reuse a tag that still has one.
// The old release is deleted through the API with the same repository-scoped
// token electron-builder uses, then the freshly built artifacts are uploaded to
// a newly created release under the same tag.
// Returns true when the tag is present on the remote. GitHub refuses to publish
// a release whose tag is missing remotely ("Published releases must have a valid
// tag"), and a same-version republish deletes the old release first, so an
// unpushed tag must stop the run rather than leave users with no release at all.
function ensureTag() {
  const tag = tagName();

  // Do NOT assume the remote is called "origin". This repo's is named after the
  // owner ("shroomygod"), and hardcoding "origin" made the push fail with
  // "'origin' does not appear to be a git repository".
  let remote = null;
  const remotes = spawnSync('git', ['remote'], { encoding: 'utf8' });
  if (remotes.status === 0) {
    const names = String(remotes.stdout || '').split(/\r?\n/).map((s) => s.trim()).filter(Boolean);
    remote = names.includes('origin') ? 'origin' : (names[0] || null);
  }
  if (!remote) {
    console.warn('  no git remote found - cannot push tag ' + tag + ' automatically.');
    return false;
  }

  try {
    const listed = spawnSync('git', ['tag', '--list', tag], { encoding: 'utf8' });
    if (listed.status !== 0) throw new Error('git tag --list failed');
    if (!listed.stdout || !listed.stdout.trim()) {
      if (spawnSync('git', ['tag', tag], { encoding: 'utf8' }).status !== 0) throw new Error('git tag failed');
      console.log('\n  created tag ' + tag);
    } else {
      console.log('\n  tag ' + tag + ' already exists locally');
    }
    // Always push, even when the tag was already present. It may have been
    // created locally and never reached the remote, which is precisely the
    // state that makes GitHub reject the release with "must have a valid tag".
    const push = spawnSync('git', ['push', remote, tag], { encoding: 'utf8' });
    if (push.status !== 0) throw new Error((String(push.stderr || push.stdout || '').trim() || 'git push failed'));
    console.log('  pushed ' + tag + ' to ' + remote);
    return true;
  } catch (e) {
    console.warn('  could not prepare tag ' + tag + ': ' + e.message);
    return false;
  }
}

// Prism Vision, the summariser and local translation ship their weights inside
// the installer so an installed Prism works offline on first use. Build without them and the feature
// still "works" — by quietly downloading hundreds of MB the first time anyone clicks it —
// so check before the build starts rather than discovering it after.
function requireModels() {
  const marker = path.join(ROOT, 'resources', 'models', 'prism-models.json');
  const tasks = require('../src/ai/tasks');
  if (!fs.existsSync(marker)) {
    fail('The AI models are not staged for this build.\n' +
         '  Prism bundles SmolVLM, SmolLM and M2M100 so local AI works offline.\n' +
         '  Run:  npm run models');
  }
  let staged;
  try {
    staged = JSON.parse(fs.readFileSync(marker, 'utf8'));
  } catch (err) {
    fail('resources/models/prism-models.json is unreadable: ' + err.message + '\n' +
         '  Run:  npm run models -- --force');
  }
  const wanted = [tasks.VISION_MODELS, tasks.TEXT_MODELS, tasks.TRANSLATION_MODEL];
  const oldTranslation = staged.models.find((m) => m.id === 'Xenova/opus-mt-en-es');
  if (oldTranslation) {
    fail('The staged models still contain the English-to-Spanish-only translator.\n' +
         '  Run:  npm run models');
  }
  for (const spec of wanted) {
    if (!staged.models.some((m) => m.id === spec.id && m.dtype === spec.dtype)) {
      fail('The staged models do not match src/ai/tasks.js (' + spec.id + ' ' + spec.dtype + ').\n' +
           '  Someone changed a model id or dtype without re-staging.\n' +
           '  Run:  npm run models -- --force');
    }
  }
  log('  models: ' + staged.models.map((m) => m.label).join(' + ') +
      ' (' + Math.round(staged.bytes / 1048576) + ' MB in the installer)');
}

// ...and check the other end of it: the staged weights actually reached
// win-unpacked. A missing extraResources entry is otherwise invisible until a
// user's first click stalls on a download.
function verifyPackagedModels() {
  const dir = path.join(ROOT, 'win-unpacked', 'resources', 'models');
  if (!fs.existsSync(dir)) {
    log('  (skipped: win-unpacked/resources/models not found)');
    return;
  }
  const tasks = require('../src/ai/tasks');
  const missing = [];
  for (const spec of [tasks.VISION_MODELS, tasks.TEXT_MODELS, tasks.TRANSLATION_MODEL]) {
    // "<resources>/models/<owner>/<repo>" — the layout transformers.js looks in.
    const modelDir = path.join(dir, ...spec.id.split('/'));
    const onnx = path.join(modelDir, 'onnx');
    let sessions = [];
    try { sessions = fs.readdirSync(onnx); } catch (_) { sessions = []; }
    if (sessions.length === 0) missing.push(spec.id + ' (no onnx/ sessions)');
    else if (!fs.existsSync(path.join(modelDir, 'config.json'))) missing.push(spec.id + ' (config.json)');
    if (spec.requiredFiles) {
      for (const file of spec.requiredFiles) {
        if (!fs.existsSync(path.join(modelDir, ...file.split('/')))) missing.push(spec.id + ' (' + file + ')');
      }
    }
  }
  if (missing.length) {
    fail('These models are missing from the built app:\n  ' + missing.join('\n  ') + '\n' +
         '  Check build.extraResources in package.json.');
  }
  log('  models: verified in win-unpacked/resources/models');
}

const GH_TOKEN = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;

// Resolve the release name before anything is built. It ends up in the GitHub
// release title and the notes heading, so a wrong choice should surface in the
// first second, not after a five-minute installer build.
const RELEASE = resolveNameForBuild();
const RELEASE_TITLE = releaseTitle(VERSION, RELEASE.name);
log('');
log('  ' + RELEASE_TITLE);
log('  name: ' + RELEASE.name + ' (' + RELEASE.source + ')');
const runnersUp = RELEASE.suggestions.slice(1).map((entry) => entry.name);
if (runnersUp.length) log('  also considered: ' + runnersUp.join(', ') + '   (override with --name)');
log('  tag:  ' + tagName() + '  (the name is not in the tag - the updater reads latest.yml, not the tag)');

// Publishing replaces any existing release for this version, so the build has to
// succeed before anything on GitHub is touched. Keep that order: build, verify,
// then replace the release and upload.
requireModels();

run('npx', ['electron-builder', '--win', 'nsis', 'portable']);

verifyArtifacts();
verifyPackagedPages();
verifyPackagedModels();

try {
  const result = releaseGit.commitAndPush(ROOT, VERSION);
  if (result.committed) log('\n  committed source changes as "' + result.commit + '"');
  else log('\n  source tree already committed; no new commit was needed');
  log('  pushed branch ' + result.branch + ' to ' + result.remote);
} catch (error) {
  fail('Could not commit and push release source: ' + error.message + '\n' +
       '  The local installer build is complete, but GitHub publishing was not started.');
}

log('\nDone. Prism ' + VERSION + ' installer and blockmap are in the project root.');

if (!GH_TOKEN) {
  console.log('\n  no GITHUB_TOKEN set - skipping the GitHub publish step.');
  console.log('  set it in this shell to publish:  $env:GITHUB_TOKEN = "ghp_..."\n');
  process.exit(0);
}

console.log('\n  GitHub token found - publishing to GitHub Releases.');
if (!ensureTag()) {
  fail('Tag ' + tagName() + ' is not on the remote. Publishing the same version replaces the\n' +
       'existing release, so the new tag must be pushed first or users would be\n' +
       'left with no release. Push it, then re-run:  git push <remote> ' + tagName());
}
(async () => {
  try {
    writeReleaseNotes(RELEASE.name);
    // electron-builder refuses to upload to a release published more than two
    // hours ago, so the same-version release is replaced first and recreated
    // from the freshly verified artifacts.
    await replaceSameVersionRelease();
    // Upload the artifacts that were just verified instead of rebuilding them.
    // latest.yml is not optional: Prism's updater reads the release's
    // latest.yml for the version and the installer SHA-512, so publishing
    // without it would leave the feed unreadable and the new build invisible.
    const uploadFiles = [
      'Prism-' + VERSION + '-x64.exe',
      'Prism-' + VERSION + '-x64.exe.blockmap',
      'Prism-' + VERSION + '-portable.exe',
      'latest.yml'
    ];
    const missingUploads = uploadFiles.filter((name) => !fs.existsSync(path.join(ROOT, name)));
    if (missingUploads.length) {
      fail('Refusing to publish: these build outputs are missing:\n  ' + missingUploads.join('\n  ') +
           '\nThe GitHub release for this version was already replaced, so fix the build and re-run.');
    }
    run('npx', ['electron-builder', 'publish', '--policy', 'always', '--version', VERSION, '--files', ...uploadFiles]);
    // electron-builder titles the release with the bare version and offers no
    // supported way to change that, so the name is applied here, after upload.
    await renamePublishedRelease(RELEASE.name);
    log('\nPublished "' + RELEASE_TITLE + '" to GitHub Releases.');
  } catch (error) {
    fail('GitHub publish failed: ' + error.message);
  }
})();