#!/usr/bin/env node
'use strict';
// release.js — one-command Prism release build (installer + blockmap).
//
// Use this INSTEAD of `npm run dist:legacy`, because icon generation has to
// happen first: electron-builder bakes win.icon into the PE at build time, so a
// stale white-background icon gets compiled straight into the .exe.
//
//   1. regenerate icons from the source logo
//   2. VERIFY the white matte is actually gone (refuse to continue otherwise)
//   3. remove artifacts from previous builds so they cannot be mistaken for
//      current ones
//   4. run electron-builder
//   5. verify the expected installer + blockmap landed
//
// Usage: npm run release

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const { PNG } = require('pngjs');

const ROOT = path.join(__dirname, '..');
const ASSETS = path.join(ROOT, 'assets');
const SIZES = [16, 24, 32, 48, 64, 128, 256, 512];

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const VERSION = pkg.version;

// Previous builds wrote Shroom-named artifacts. They cannot be salvaged by
// renaming: the product name and the icon are compiled into the PE, so only a
// rebuild replaces them. Listed explicitly rather than globbed, so this can
// never reach anything else sitting in the project root.
// Matches a built installer or blockmap for ANY version, old brand or new:
//   Prism-1.0.2-x64.exe   Prism-1.0.2-portable.exe   Prism-1.0.2-x64.exe.blockmap
//   ShroomBrowser-1.0.1-x64.exe  (etc.)
// A hardcoded version list left every previous release behind, so the root
// accumulated one installer set per build. Cleaning by pattern keeps exactly one
// set - the portable and x64 installers plus the x64 blockmap. The shape is
// strict, so nothing that is not a Prism/ShroomBrowser build artifact can match;
// Prism-1.0.2-x64.__uninstaller.exe deliberately does not (and is created during
// the build, after this runs).
const ARTIFACT_RE = /^(?:Prism|ShroomBrowser)-[\d.]+-(?:x64|portable)(?:\.exe|\.exe\.blockmap)$/;

// latest.yml is regenerated by electron-builder only when a `publish` block is
// configured. The stale copy survived every build still pointing at
// PrismBrowser-1.0.2-x64.exe - an old-brand name for a file that does not exist.
const STALE_ARTIFACTS = ['latest.yml'];



function log(msg) { console.log(msg); }
function fail(msg) { console.error('\nERROR: ' + msg + '\n'); process.exit(1); }

// shell:false when we spawn node directly. On Windows, routing an absolute
// path like "C:\Program Files\nodejs\node.exe" through cmd.exe re-splits it on
// the space and the command fails for a reason that looks nothing like a path
// bug.
function run(cmd, args, useShell = true) {
  log('\n> ' + cmd + ' ' + args.join(' '));
  const r = spawnSync(cmd, args, { cwd: ROOT, stdio: 'inherit', shell: useShell });
  if (r.error) fail(r.error.message);
  if (typeof r.status === 'number' && r.status !== 0) fail(cmd + ' exited with code ' + r.status);
}

function generateIcons() {
  run(process.execPath, ['scripts/process-logo.js'], false);
}

// The defect this guards against: process-logo.js reads a white-background
// render. If the matte is not knocked out, the artwork bounds cover the entire
// canvas and every icon ships as a white square — which looks blank on Prism's
// dark chrome rather than obviously wrong. Sampling the border is enough to
// tell a real transparent icon from a white one, and costs almost nothing.
function verifyIconsTransparent() {
  for (const s of SIZES) {
    const file = path.join(ASSETS, 'icon-' + s + '.png');
    if (!fs.existsSync(file)) fail('missing ' + file + ' — icon generation did not produce it');
    const png = PNG.sync.read(fs.readFileSync(file));
    let opaque = 0;
    const at = (x, y) => png.data[(y * png.width + x) * 4 + 3];
    for (let x = 0; x < png.width; x++) {
      if (at(x, 0) === 255) opaque++;
      if (at(x, png.height - 1) === 255) opaque++;
    }
    for (let y = 0; y < png.height; y++) {
      if (at(0, y) === 255) opaque++;
      if (at(png.width - 1, y) === 255) opaque++;
    }
    if (opaque > 0) {
      fail('icon-' + s + '.png still has ' + opaque + ' fully opaque border pixels.\n' +
           '  The white background was not knocked out, so this icon is a white\n' +
           '  square that reads as a blank tile on Prism\'s dark chrome.\n' +
           '  Raise OPAQUE_FLOOR in scripts/process-logo.js and re-run.');
    }
  }
  log('OK  all ' + SIZES.length + ' icon sizes have transparent borders');
}

function removeIfPresent(target) {
  if (!fs.existsSync(target)) return false;
  fs.rmSync(target, { force: true, recursive: true });
  log('  removed ' + path.relative(ROOT, target));
  return true;
}

function cleanStale() {
  log('\nCleaning previous-build artifacts:');
  let n = 0;
  for (const entry of fs.readdirSync(ROOT)) {
    if (ARTIFACT_RE.test(entry)) { removeIfPresent(path.join(ROOT, entry)); n++; }
  }
  for (const name of STALE_ARTIFACTS) if (removeIfPresent(path.join(ROOT, name))) n++;
  if (removeIfPresent(path.join(ROOT, 'win-unpacked'))) n++;
  // dist/ is a whole earlier output location, from when directories.output was
  // "./dist". It still holds a ShroomBrowser blockmap and a second stale
  // win-unpacked/ with the old logo inside its .exe. The current config writes
  // to the project root, so nothing recreates it — remove the whole directory.
  if (removeIfPresent(path.join(ROOT, 'dist'))) n++;
  // Build OUTPUTS only. This deliberately does not touch assets/shroom.ico,
  // assets/ShroomIcon-raw.png or the src/main/shroom-search*.js forwarders:
  // deleting source from a build command means that if anyone ever re-adds a
  // require() of one of those stubs, `npm run release` silently deletes a
  // source file instead of reporting a broken import. Those leftovers are
  // harmless and unreferenced; remove them by hand.
  if (!n) log('  nothing to clean');
}

// Read the packaged asar back and assert the entry point and every internal
// page really made it in. `files` in package.json is a glob list, so a silent
// packaging regression is otherwise invisible until the installed app shows a
// blank page — which is exactly the failure this guards against.
function verifyPackagedPages() {
  const asarPath = path.join(ROOT, 'win-unpacked', 'resources', 'app.asar');
  if (!fs.existsSync(asarPath)) {
    log('  (skipped: win-unpacked/resources/app.asar not found)');
    return;
  }
  let asar = null;
  for (const name of ['@electron/asar', 'asar']) {
    try { asar = require(name); break; } catch (_) { /* try the next name */ }
  }
  if (!asar) {
    log('  (skipped: no asar module available to inspect the archive)');
    return;
  }
  const needed = [
    'src/main/main.js',
    'src/shell/shell.css',
    'src/pages/newtab.html',
    'src/pages/search.html',
    'src/pages/history.html',
    'src/pages/bookmarks.html',
    'src/pages/downloads.html',
    'src/pages/passwords.html',
    'src/pages/extensions.html',
    'src/pages/privacy.html',
    'src/pages/settings.html',
    'src/pages/blocked.html',
    'src/pages/error.html'
  ];
  // Read each entry straight out of the archive rather than comparing against
  // a listing. listPackage() formats paths differently across asar versions
  // (leading slash or not, and the Rust rewrite may differ again), and getting
  // that wrong reports every file as missing on a perfectly good build.
  if (typeof asar.extractFile !== 'function') {
    log('  (skipped: asar module has no extractFile)');
    return;
  }
  const missing = [];
  for (const f of needed) {
    // On Windows the archive stores entries with backslash separators
    // ("\src\main\main.js"). extractFile() looks up by exact path, so a
    // forward-slash lookup misses every entry and reports a perfectly good
    // build as empty. Try both spellings.
    let found = false;
    for (const variant of [f, f.replace(/\//g, path.sep), f.replace(/\//g, '\\')]) {
      try { asar.extractFile(asarPath, variant); found = true; break; }
      catch (_) { /* try the next spelling */ }
    }
    if (!found) missing.push(f);
  }
  if (missing.length) {
    let sample = '';
    try {
      const list = asar.listPackage(asarPath) || [];
      sample = '\n  First entries in the archive: ' + JSON.stringify(list.slice(0, 6));
      const srcish = list.filter((e) => /main|pages|shell/i.test(e));
      sample += '\n  Entries matching main|pages|shell: ' + JSON.stringify(srcish.slice(0, 6)) +
                '  (' + srcish.length + ' total)';
    } catch (e) {
      sample = '\n  (could not list the archive: ' + e.message + ')';
    }
    // Reported, not fatal. This check runs after the artifacts already exist,
    // so failing here cannot protect anything - it can only block installation
    // of a perfectly good installer. It has produced false positives twice
    // (asar stores backslash-separated paths on Windows), and a checker with no
    // track record should not hold veto power. Treat what it prints as a reason
    // to look, not as a reason to stop.
    console.error(
      '\nWARNING: could not confirm the packaged app.asar contains ' + missing.length + ' file(s):\n' +
      '  ' + missing.join('\n  ') + sample + '\n' +
      '  The installer HAS been built. Install it; if internal pages render blank,\n' +
      '  this is the thing to investigate.\n');
    return;
  }
  log('OK  app.asar contains the entry point and all ' + needed.length + ' internal pages');
}

function verifyArtifacts() {
  // directories.output is "./", so artifacts land in the project root.
  const expected = [
    'Prism-' + VERSION + '-x64.exe',
    'Prism-' + VERSION + '-x64.exe.blockmap',
    'Prism-' + VERSION + '-portable.exe'
  ];
  const missing = expected.filter((name) => !fs.existsSync(path.join(ROOT, name)));
  log('\nArtifacts in ' + ROOT + ':');
  for (const name of expected) {
    if (missing.includes(name)) { log('  MISSING  ' + name); continue; }
    const mb = (fs.statSync(path.join(ROOT, name)).size / (1024 * 1024)).toFixed(1);
    log('  OK       ' + name + '  (' + mb + ' MB)');
  }
  if (missing.length) {
    fail('electron-builder finished but ' + missing.length + ' expected artifact(s) are missing:\n' +
         '  ' + missing.join('\n  ') + '\n' +
         '  Check the electron-builder output above for the real cause.');
  }
}

log('Prism ' + VERSION + ' release build');
log('='.repeat(46));

if (!fs.existsSync(path.join(ROOT, 'node_modules', 'electron-builder'))) {
  fail('electron-builder is not installed. Run `npm install` first.');
}

generateIcons();
verifyIconsTransparent();
cleanStale();

run('npx', ['electron-builder', '--win', 'nsis', 'portable']);

verifyArtifacts();
verifyPackagedPages();
log('\nDone. Prism ' + VERSION + ' installer and blockmap are in the project root.');